# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-12 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.TextField(blank=True, db_column='CONTROL_ID', null=True)),
                ('symptom', models.TextField(blank=True, db_column='SYMPTOM', null=True)),
                ('location', models.TextField(blank=True, db_column='LOCATION', null=True)),
                ('intensity', models.IntegerField(blank=True, db_column='INTENSITY', null=True)),
                ('comments', models.TextField(blank=True, db_column='COMMENTS', null=True)),
                ('img_url', models.TextField(blank=True, db_column='IMG_URL', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SYMPTOMS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('control_id', models.TextField(blank=True, db_column='CONTROL_ID', null=True)),
                ('first_name', models.TextField(blank=True, db_column='FIRST_NAME', null=True)),
                ('last_name', models.TextField(blank=True, db_column='LAST_NAME', null=True)),
                ('dob', models.TextField(blank=True, db_column='DOB', null=True)),
                ('email', models.TextField(blank=True, db_column='EMAIL', null=True)),
                ('doctor_email', models.TextField(blank=True, db_column='DOCTOR_EMAIL', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'USER',
            },
        ),
    ]
